apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "false"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: password

      volumes:
        - name: app-code
          hostPath:
            path: /c/Users/valfr/Documents/PhpstormProjects/my-deal
            type: Directory
        - name: nginx-config-volume
          configMap:
            name: nginx-config
