name: Deploy to VPS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT || 22 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create target directory on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT || 22 }}
          script: |
            mkdir -p /home/${{ env.SSH_USERNAME }}/app_manifests/

      - name: Install K3s on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT || 22 }}
          script: |
            curl -sfL https://get.k3s.io | sh -s - \
              --node-ip ${{ env.SERVER_IP }} \
              --disable traefik \
              --flannel-backend=host-gw

      - name: Verify K3s Installation
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT || 22 }}
          script: |
            kubectl get nodes

      - name: Copy app to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT || 22 }}
          source: "./*"
          target: "/var/www/app/"

      - name: Copy Kubernetes manifests to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT || 22 }}
          source: "kubernetes/*"
          target: "/home/${{ env.SSH_USERNAME }}/app_manifests/"

      - name: Create env on K3s cluster
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT || 22 }}
          script: |
            kubectl create secret generic secret \
              --from-literal=password=${{ secrets.SSH_USERNAME }} \
              --dry-run=client -o yaml | kubectl apply -f -


      - name: Apply manifests using kubectl
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT || 22 }}
          script: |
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            kubectl apply -f /home/${{ env.SSH_USERNAME }}/app_manifests/kubernetes

      - name: Install dependencies
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT || 22 }}
          script: |
            POD_NAME=$(kubectl get pods -l app=php-fpm -o jsonpath='{.items[0].metadata.name}')
            cd /var/www/app
            kubectl exec "$POD_NAME" -- composer install \
              --no-dev \
              --optimize-autoloader \
              --no-interaction \
              --no-progress
            kubectl exec "$POD_NAME" -- npm install && npm run build
