name: Deploy to VPS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create target directory on VPS
        uses: appleboy/ssh-action@v1.2.0
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT || 22 }}
        with:
          envs: SERVER_IP, SSH_USERNAME, SSH_PRIVATE_KEY, SSH_PORT
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT || 22 }}
          script: |
            mkdir -p /home/${{ secrets.SSH_USERNAME }}/app_manifests/

      - name: Install K3s on VPS
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_rsa \
              ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} '
              curl -sfL https://get.k3s.io | sh -s - \
                --node-ip ${{ secrets.SERVER_IP }} \
                --disable traefik \
                --disable servicelb \
                --flannel-backend=host-gw
          '

      - name: Verify K3s Installation
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_rsa \
              ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} '
              sudo kubectl get nodes
          '

      - name: Copy Kubernetes manifests to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: "kubernetes/*"  # Path to your manifests in the repository
          target: "/home/${{ secrets.SSH_USERNAME }}/app_manifests/"

      - name: Apply manifests using kubectl
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            kubectl apply -f /home/${{ secrets.SSH_USERNAME }}/app_manifests/
